In [40]:
import numpy as np
data1=np.zeros((10,5), dtype='int')
data1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [41]:
data1[0,:]=np.arange(1,6)

In [42]:
data1

array([[1, 2, 3, 4, 5],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [43]:
data1[0,:]=np.arange(6,11)
data1

array([[ 6,  7,  8,  9, 10],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [44]:
data1[1,:]=np.arange(6,11)
data1

array([[ 6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [45]:
data1[2,:]=np.arange(11,16)
data1

array([[ 6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [46]:
data1[3,:]=np.arange(16,21)
data1

array([[ 6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [19]:
data1[4,:]=np.arange(21,26)
data1

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [20]:
data1[5,:]=np.arange(26,31)
data1

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.],
       [26., 27., 28., 29., 30.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [21]:
data1[6,:]=np.arange(31,36)
data1

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.],
       [26., 27., 28., 29., 30.],
       [31., 32., 33., 34., 35.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [22]:
data1[7,:]=np.arange(36,41)
data1

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.],
       [26., 27., 28., 29., 30.],
       [31., 32., 33., 34., 35.],
       [36., 37., 38., 39., 40.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [23]:
data1[8,:]=np.arange(41,46)
data1

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.],
       [26., 27., 28., 29., 30.],
       [31., 32., 33., 34., 35.],
       [36., 37., 38., 39., 40.],
       [41., 42., 43., 44., 45.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [24]:
data1[9,:]=np.arange(46,51)
data1

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.],
       [26., 27., 28., 29., 30.],
       [31., 32., 33., 34., 35.],
       [36., 37., 38., 39., 40.],
       [41., 42., 43., 44., 45.],
       [46., 47., 48., 49., 50.]])

In [48]:
data2=np.zeros((5,10), dtype='int')
data2

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [49]:
data2[:,0]=np.arange(1,6)
data2

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [3, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [4, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [5, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [50]:
data2[:,1]=np.arange(6,11)
data2

array([[ 1,  6,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 2,  7,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 3,  8,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 4,  9,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 5, 10,  0,  0,  0,  0,  0,  0,  0,  0]])

In [51]:
data2[:,2]=np.arange(11,16)
data2

array([[ 1,  6, 11,  0,  0,  0,  0,  0,  0,  0],
       [ 2,  7, 12,  0,  0,  0,  0,  0,  0,  0],
       [ 3,  8, 13,  0,  0,  0,  0,  0,  0,  0],
       [ 4,  9, 14,  0,  0,  0,  0,  0,  0,  0],
       [ 5, 10, 15,  0,  0,  0,  0,  0,  0,  0]])

In [52]:
data2[:,3]=np.arange(16,21)
data2

array([[ 1,  6, 11, 16,  0,  0,  0,  0,  0,  0],
       [ 2,  7, 12, 17,  0,  0,  0,  0,  0,  0],
       [ 3,  8, 13, 18,  0,  0,  0,  0,  0,  0],
       [ 4,  9, 14, 19,  0,  0,  0,  0,  0,  0],
       [ 5, 10, 15, 20,  0,  0,  0,  0,  0,  0]])

In [53]:
data2[:,4]=np.arange(21,26)
data2

array([[ 1,  6, 11, 16, 21,  0,  0,  0,  0,  0],
       [ 2,  7, 12, 17, 22,  0,  0,  0,  0,  0],
       [ 3,  8, 13, 18, 23,  0,  0,  0,  0,  0],
       [ 4,  9, 14, 19, 24,  0,  0,  0,  0,  0],
       [ 5, 10, 15, 20, 25,  0,  0,  0,  0,  0]])

In [54]:
data2[:,5]=np.arange(26,31)
data2

array([[ 1,  6, 11, 16, 21, 26,  0,  0,  0,  0],
       [ 2,  7, 12, 17, 22, 27,  0,  0,  0,  0],
       [ 3,  8, 13, 18, 23, 28,  0,  0,  0,  0],
       [ 4,  9, 14, 19, 24, 29,  0,  0,  0,  0],
       [ 5, 10, 15, 20, 25, 30,  0,  0,  0,  0]])

In [55]:
data2[:,6]=np.arange(31,36)
data2

array([[ 1,  6, 11, 16, 21, 26, 31,  0,  0,  0],
       [ 2,  7, 12, 17, 22, 27, 32,  0,  0,  0],
       [ 3,  8, 13, 18, 23, 28, 33,  0,  0,  0],
       [ 4,  9, 14, 19, 24, 29, 34,  0,  0,  0],
       [ 5, 10, 15, 20, 25, 30, 35,  0,  0,  0]])

In [56]:
data2[:,7]=np.arange(36,41)
data2

array([[ 1,  6, 11, 16, 21, 26, 31, 36,  0,  0],
       [ 2,  7, 12, 17, 22, 27, 32, 37,  0,  0],
       [ 3,  8, 13, 18, 23, 28, 33, 38,  0,  0],
       [ 4,  9, 14, 19, 24, 29, 34, 39,  0,  0],
       [ 5, 10, 15, 20, 25, 30, 35, 40,  0,  0]])

In [57]:
data2[:,8]=np.arange(41,46)
data2

array([[ 1,  6, 11, 16, 21, 26, 31, 36, 41,  0],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42,  0],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43,  0],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44,  0],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45,  0]])

In [58]:
data2[:,9]=np.arange(46,51)
data2

array([[ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50]])

In [68]:
 np.savetxt('practice.txt', data2)


In [69]:
my_data=np.loadtxt('practice.txt')

In [70]:

my_data

array([[ 1.,  6., 11., 16., 21., 26., 31., 36., 41., 46.],
       [ 2.,  7., 12., 17., 22., 27., 32., 37., 42., 47.],
       [ 3.,  8., 13., 18., 23., 28., 33., 38., 43., 48.],
       [ 4.,  9., 14., 19., 24., 29., 34., 39., 44., 49.],
       [ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.]])

In [71]:
import pandas as pd


In [74]:
data_read=pd.read_csv('practice.txt',header=None)

In [75]:
data_read

0
0  1.000000000000000000e+00 6.000000000000000000e...
1  2.000000000000000000e+00 7.000000000000000000e...
2  3.000000000000000000e+00 8.000000000000000000e...
3  4.000000000000000000e+00 9.000000000000000000e...
4  5.000000000000000000e+00 1.000000000000000000e...

In [84]:
x=float(input("input a number"))
y=x**2-1
y

input a number56.9


3236.6099999999997

x=4
y=3
z=x**2+y**

In [3]:
x=float(input("input x number"))
y=float(input("input y number"))
z=x**2+y**2
z

input x number2
input y number6


40.0

In [4]:
z

40.0

In [1]:
a=float(input("input coefficient a number"))
b=float(input("input coefficient b number"))
c=float(input("input coefficient c number"))
x=float(input("input coefficient x number"))
d=a*x**2+b*x+c
d



input coefficient a number2
input coefficient b number4
input coefficient c number5
input coefficient x number7


131.0

In [5]:
 a=[12,23,34,45,56,67,78]
print(a[3:5])

[45, 56]


In [6]:
a=[12,23,34,45,56,67,78]
print(a[2:7])

[34, 45, 56, 67, 78]


In [8]:
a=[12,23,34,45,56,67,78]
print(a[:3])

[12, 23, 34]


In [10]:
a=[12,23,34,45,56,67,78]
print(a[4:])

[56, 67, 78]


In [17]:
a=[43,44,53,54,63,64,73,74]
print(a[-4:-2])

[63, 64]


In [23]:
a=[[45,46,56],[34,38,52],[68,77,82]]
print(a)

[[45, 46, 56], [34, 38, 52], [68, 77, 82]]


In [26]:
print(a[1][2])

52


In [31]:
a=[56,43,98]
b=[23,65,12]
c=a+b
print(c)


[56, 43, 98, 23, 65, 12]


In [32]:
a=[56,43,77]
a.append(23)
print(a)

[56, 43, 77, 23]


In [35]:
a=[23,45,87,56,89,45]
a.insert(0,12)
print(a)

[12, 23, 45, 87, 56, 89, 45]


In [37]:
a=[23,45,87,56,89,63]
5 in a

False

In [39]:
a=[1,2,3]
b=[4,5,6]
c = zip(a,b)

In [40]:
a=(2,3,4)
a

(2, 3, 4)

In [41]:
type(a)

tuple

In [42]:
print(a[2])

4


In [47]:
a="my name is N.rakesh"
print(a[3:7])

name


In [48]:
a="rakesh is good boy"
a.find("rakesh")

0

In [51]:
import numpy as np
mydata=np.arange(100,dtype="float")
mydata.shape=(10,10)

In [52]:
mydata

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
       [50., 51., 52., 53., 54., 55., 56., 57., 58., 59.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.],
       [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
       [80., 81., 82., 83., 84., 85., 86., 87., 88., 89.],
       [90., 91., 92., 93., 94., 95., 96., 97., 98., 99.]])

In [56]:
mydata=np.arange(25,dtype="float")
mydata.shape=(5,5)
mydata

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [58]:
mydata=np.arange(90,dtype="float")
mydata.shape=(3,30)
mydata

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
        26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41., 42.,
        43., 44., 45., 46., 47., 48., 49., 50., 51., 52., 53., 54., 55.,
        56., 57., 58., 59.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69., 70., 71., 72.,
        73., 74., 75., 76., 77., 78., 79., 80., 81., 82., 83., 84., 85.,
        86., 87., 88., 89.]])

In [8]:
import numpy as np
a=np.arange(12, dtype='int')
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [9]:
print(a[3:])

[ 3  4  5  6  7  8  9 10 11]


In [73]:
phonebook={}
phonebook["rakesh"] ="9666601061"
phonebook["suresh"]="9849924974"
print(phonebook)

{'rakesh': '9666601061', 'suresh': '9849924974'}


In [82]:
sarees={}
sarees["green"]="2"
print(sarees)

{'green': '2'}


In [78]:
print(sarees["green"])

2


In [80]:
sarees.has_key("blue")

AttributeError: 'dict' object has no attribute 'has_key'

In [83]:
len(sarees)

1

In [41]:
names=["ram","raj","ravi","rahul","rahim","raju","rakesh","ramesh","will","ranbir"]
year=[91,92,93,94,95,96,97,98,1991,92,95]
name=input("Enter your friends name:")
print("you have",len(names),"friends")
index=names.index(name)
print(name,"is number",index, "in your list")
print(name, "was born in",year[index])


Enter your friends name:will
you have 10 friends
will is number 8 in your list
will was born in 1991


In [38]:
#create 3 lists fruits, shop, price

#out put
# if you select a fruit shop name name in which it is available should be displayed with price

In [10]:
fruits=['apple','banana','mango','pineapple']
shop=[2,55,3,65]
price=[30,40,50,60]
value=input('enter fruits name:')
index1=fruits.index(value)
index2=shop[index1]
index3=price[index1]
print('you have',value,'in',index2,'shop')
print(value,'the price is',index3)


enter fruits name:mango
you have mango in 3 shop
mango the price is 50


In [2]:
student=['rakesh','rajesh','srivani','abhishek','srilatha','ashwini','vikesh','nikhitha']
roll=[46,65,12,34,54,64,34,89]
standard=['3rd class','4th class','5th class','6th class','7th class','8th class','9th class','10th class']
gender=['male','male','female','male','female','female','male','female']
take=input('enter student name:')
index1=student.index(take)
index2=roll[index1]
index3=standard[index1]
index4=gender[index1]
print('rakesh roll number is',index2)
print(take,'studies in',index3)
print(take,'gender is',index4)


enter student name:rajesh
rakesh roll number is 65
rajesh studies in 4th class
rajesh gender is male


In [20]:
mohanlal=['saritha','srilatha','mamatha','shashikala']
place=['nizamabad','nizamabad','hyderabad','nizamabad']
dob=['12dec','18thsept','21stfeb','6thapril']
n=input("enter mohanlal's daughter's name:")
index1=mohanlal.index(n)
index2=place[index1]
index3=dob[index1]
print(n,'lives in',index2)
print(n,'born on',index3)


enter mohanlal's daughter's name:saritha
saritha lives in nizamabad
saritha born on 12dec
